DROP TABLE IF EXISTS TARJETA;
DROP TABLE IF EXISTS CUOTA;
DROP TABLE IF EXISTS DIAPAGO;
  
CREATE TABLE TARJETA (
  id INT not null AUTO_INCREMENT  PRIMARY KEY,
  tipoTarjeta VARCHAR(20) NOT NULL,
  tea VARCHAR(10) NOT NULL
);

CREATE TABLE CUOTA (
  id INT not null AUTO_INCREMENT  PRIMARY KEY,
  numcuota VARCHAR(5) NOT NULL
);

CREATE TABLE DIAPAGO (
  id INT not null AUTO_INCREMENT  PRIMARY KEY,
  numdia VARCHAR(5) NOT NULL
);

